### PR TITLE
Add useRef flag to useReducer to conditionally enable useRef (default is false)

### PR DESCRIPTION
**Pull request by andywhite37**
This adds a flag `~useRef=false` to `ReludeReact.Reducer.useReducer` so we can conditionally turn on/off the ref wrapper that was previously added in #23 .

I made the default `~useRef=false`, which means the default behavior will be the way it worked originally, where unmanaged side effects might run multiple times if they are present in the reducer function. I did this, because we've been led to believe that this is the expected behavior of `React.useReducer` - https://twitter.com/dan_abramov/status/1102631338853715973?s=20 . I was also running into problems with the `useRef` wrapper where prop updates were not making their way into the reducer function, I think b/c of a closure/memoization that occurs when the reducer is wrapped in a `Ref`.

To get the `useRef` wrapper, which was added by @jihchi in #23 , use `ReludeReact.Reducer.useReducer(~useRef=true, reducer, initialState)`

I updated the tests to test for each case, just to ensure our assumptions are checked over time.

### CODE REVIEW

**Comment by andywhite37** [comment]
I'm planning to merge this maybe tomorrow afternoon, unless anyone has feedback.

**Comment by jihchi** [comment]
Hi @andywhite37 , maybe we could get rid of `useRef` wrapper (#23 but keep the test case) since it is a work-around and adding some complexity.

**Comment by andywhite37** [comment]
@jihchi - that works for me given that effects in the reducer are not recommended, and we have a mechanism to control them. I'll leave this for a little longer to see if anyone has any more feedback, then I'll go ahead and remove that `useRef` and the new flag (but I'll leave the test case).

**Comment by andywhite37** [comment]
Ok, I removed, the `useRef` stuff completely. The behavior of unmanaged side effects will now return to how it worked before, where unmanaged side effects in useReducer functions might run more than once. Side-effects can be managed in the reducer using the `SideEffect`/`IO`-based update values that you can return from the reducer.

**Pull request merged**
