### PR TITLE
Update docs and fix reducer definition

### PR DESCRIPTION
**Pull request by arecvlohe**
## Background

After installing the latest release I found some errors in my code locally. I tracked down the issue to the reducer's signature. I looked at the docs and also noticed they were not up to date with the latest changes so I updated it as well.

## Summary

- Update docs to reflect current API
- Update docs to have one space after periods instead of 2 (not really important but it's something my editor did and I agreed with the change)
- Update the reducer type definition to reflect usage

### CODE REVIEW

**Comment by andywhite37** [comment]
@arecvlohe - thanks for the PR.  Yeah, @mlms13 recently changed the order of the arguments for the `useReducer` from `(initialState, reduce)` to `(reduce, initialState)` to be more consistent with the default `React.useReducer` signature, and the reduce function from `(action, state) => {}` to `(state, action) => { }`, because that way you can do something like `let reduce = (state) => fun | Action1(...) =>`

As far as the change you're proposing to make it `type reducer('state, 'action)` rather than `type reducer('action, 'state)` - we have a bunch of types in this library that have a signature like `t('action, 'state)`, so if we're going to make that change, I'd like to do it consistently everywhere.  That desire for consistency was the main reason we didn't change all the types when @mlms13 made the change to the order of arguments in `useReducer` and the reduce function itself.

Since the `reduce` function takes the arguments now as `(state, action) => { }` I could see an argument to make the types `type t('state, 'action)`, but I would just like for all these to be consistent.  (See also the `SideEffect` module).

Is it worth changing all the types from `t('action, 'state)` to `t('state, 'action)` in one big breaking change?  I think I'm leaning more towards leaving the types themselves as `t('action, 'state)`, but I could be convinced to change it, but only if it's consistent.

**Comment by arecvlohe** [comment]
@andywhite37 So the `useReducer` update to the docs makes sense and I think we are on the same page about that one.

I think the misunderstanding is on line 41 in `ReludeReact_Reducer.re`:
```reason
type reducer('action, 'state) = ('state, 'action) => update('action, 'state);
```

You notice the types and the arguments are flipped. I think that's where the issue arose in my project. I am perfectly fine with flipping the args and not the types if that what was intended. As far as I am concerned, I am not trying to propose any critical change to the API in this PR. Just trying get things working correctly 🙂

**Comment by andywhite37** [comment]
Yeah, @mlms13 changed the order of function arguments for `useReducer` and the actual `reducer` function to make it more similar to the `React.useReducer` with the state argument being last.  The docs were indeed wrong after this change - it looks like the code example didn't get updated.  The type params in `type reducer('action, 'state)` don't actually need to match the order in which they are used in the definition `= ('state, 'action) => update('action, 'state)`, so I don't think we should need to flip those type params as you've done.

I think I'd prefer to keep the `type reducer('action, 'state)` as it currently is, as it matches a bunch of other types in the library, and I'm not sure the types are worth changing at this point.  In your project, I think the only changes you should need to make are to switch the order of arguments for `useReducer` and the `reducer` function to make the state argument last.  I don't think you or we should need to change the `reducer` type for this - just the order of function arguments for `useReducer` and the `reducer` function.

If your code is open source and you can point me to the place where you're having a problem, I can take a look if you want.

**Comment by arecvlohe** [comment]
> The type params in type reducer('action, 'state) don't actually need to match the order in which they are used in the definition = ('state, 'action) => update('action, 'state), so I don't think we should need to flip those type params as you've done.

Oh okay. I think I am just confused by the whole thing then, how you can have a type signature that doesn't match the argument order. I can remove my changes to `type reducer` and anywhere I might have changed it in the docs and leave the `useReducer` docs update.

**Comment by andywhite37** [comment]
I think it's confusing because it's less common to make an actual `type` for a function like below.  In this, the order of the type params in the type don't matter compared to the function itself:

```reason
type reducer('action, 'state) = ('state, 'action) => update('action, 'state);
```

It's more common to create a let binding for a function and type it like this:

```reason
// More common way of annotating types for a function in reason
let reduce = (state: 'state, action: 'action) => NoUpdate;

// Less common way of annotating the types of a function
// I think this is what you might be thinking about for the type param ordering
let reduce: ('state, 'action) => update('action, 'state) = (state, action) => NoUpdate;
```

You can also type the let binding like this though:

```reason
// Even less common way of annotating function type
let reduce: reducer('action, 'state) = (state, action) => NoUpdate;
```

Or just omit the types and rely on inference:

```reason
let reduce = (state, action) => NoUpdate;
```

**Comment by andywhite37** [comment]
I went ahead and fixed the docs.  I'll just close this PR for now, but let me know if you see any other doc issues or if you think we need more discussion here.

**Comment by arecvlohe** [comment]
@andywhite37 Thanks for the clarification! That was definitely tricky for me. Wasn't even aware of all those ways of typing out the signatures.

**Pull request closed without merging**
